services:
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: labs-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: INFO
      KC_HEALTH_ENABLED: true
    # volumes:
    #   - ./config/keycloak/minhacomanda-realm.json:/opt/keycloak/data/import/minhacomanda-realm.json:ro
    ports:
      - "8080:8080"
    command:
      - start-dev
      - --import-realm
    networks:
      - keycloak-network

networks:
  keycloak-network:
    name: labs-keycloak-network
    driver: bridge